# there's a bunch of metadata in here that might only really make sense in dbt cloud
# In the deployments I've been involved with I've found that there's no discernable value in setting these values.
# As such I set these parameters to generic values that line everything up in a given repo.
name: 'product' # only referred to in this config file
version: '1.0.0'
config-version: 2

flags:
  send_anonymous_usage_stats: false
  use_colors: true

# This setting configures which "profile" dbt uses for this project.
profile: 'current'

vars:
  docs_url: https://github.com/brabster/pypi_vulnerabilities
  location: '{{ env_var("DBT_LOCATION") }}'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models", "test_models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# colours based on https://doc.bplogix.com/content/implementersreference/accessibility_principle_perceivable_contrast.htm

models:
  +docs:
    node_color: "#000066"
  +labels:
    stability: unstable
    data_classification: public
  +persist_docs:
    relation: true
    columns: true
  product:
    published:
      udfs:
        +docs:
          node_color: "#333333"
    internal:
      +schema: internal
      udfs:
        +docs:
          node_color: "#333333"
    billing:
      +schema: billing
    udf_tests:
      materialized: ephemeral
      +docs:
        node_color: "#555555"

tests:
  product:
    contracts:
      +docs:
        node_color: "#B10000"
    udfs:
      +docs:
        node_color: "#555555"
    +docs:
      node_color: "#0000FF"
