# there's a bunch of metadata in here that might only really make sense in dbt cloud
# In the deployments I've been involved with I've found that there's no discernable value in setting these values.
# As such I set these parameters to generic values that line everything up in a given repo.
name: 'product' # only referred to in this config file
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'current'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models", "test_models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# can document seeds if present
# seeds:
#   +persist_docs:
#     relation: true
#     columns: true

models:
  +grant_access_to: []
  +persist_docs:
    # push any model/column descriptions to the target database
    relation: true
    columns: true
  product:
    udf_tests:
      materialized: ephemeral

tests: {}

on-run-start:
  - "{{ ensure_target_dataset_exists() }}"
  - "{{ ensure_udfs() }}"
  - "{{ ensure_single_day_downloads_materialized() }}"