
name: dbt build in venv
description: Runs dbt build from venv
inputs:
  env:
    required: true
    description: Environment file to source
  dbt_extra_args:
    required: false
    default: ''
    description: Extra CLI arguments to supply to DBT
runs:
  using: composite
  steps:
    - name: dbt build for ${{ inputs.env }}
      shell: bash
      run: |
          source .venv/bin/activate
          source .envs/${{ inputs.env }}/.env
          dbt build --exclude contracts ${{ inputs.dbt_extra_args }}
          dbt docs generate
      
    - name: upload target artifacts
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: dbt_artifacts_${{ inputs.env }}
        path: |
          target
          logs



