
name: Setup DBT in virtualenv
description: Sets up environment suitable for DBT

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      env:
        PIP_REQUIRE_VIRTUALENV: false
      with:
        python-version: '3.11' # dbt does not support 3.12 yet
        check-latest: true
    - name: setup-python-venv
      shell: bash
      run: |
        python --version
        python -m venv .venv
        source .venv/bin/activate
        pip install -U setuptools pip safety
        pip install -U -r requirements.txt
        dbt deps
    # - name: safety-check maybe issue
    #   shell: bash
    #   run: |
    #     source .venv/bin/activate
    #     safety check
