name: Perform default Python/GCP/dbt workflow setup

inputs:
  workload_identity_provider:
    required: true
  service_account:
    required: true

runs:
  using: composite
  steps:
    - name: impersonate_gcp_sa
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: test_auth
      shell: bash
      run: bq ls

    - name: setup_python
      uses: ./.github/actions/setup_python