on:
  workflow_dispatch: {}
  workflow_call: {}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PIP_REQUIRE_VIRTUALENV: true
      DBT_MAX_GIGABYTES_BILLED: ${{ vars.DBT_MAX_GIGABYTES_BILLED }}
    permissions:
        contents: read
        id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup_workflow
        uses: ./.github/actions/setup_default_workflow
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      - name: load_prod_safety_db
        uses: ./.github/actions/run_in_venv
        with:
          working-dir: .
          script: |
            dbt run-operation ensure_datasets
            python etl/safety_db/load_missing_partitions.py --dataset ${DBT_DATASET}_internal