name: deploy-to-gcp-new

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '0 4 * * SAT'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PIP_REQUIRE_VIRTUALENV: true
      DBT_PYPI_EARLIEST_DOWNLOAD_DATE: ${{ vars.DBT_PYPI_EARLIEST_DOWNLOAD_DATE }}
      DBT_MAX_GIGABYTES_BILLED: ${{ vars.DBT_MAX_GIGABYTES_BILLED }}
    permissions:
        contents: read
        id-token: write
        actions: read
        pages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_workflow
        uses: ./.github/actions/setup_default_workflow
      
      - name: ensure_schema_objects
        uses: ./.github/actions/run_cli
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          script: |
            dbt debug
            dbt deps
            dbt run-operation ensure_datasets
      
      - name: load prod safety db
        uses: ./.github/actions/run_cli
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          script: |
            python etl/safety_db/load_missing_partitions.py --dataset ${DBT_DATASET}_internal
      
      - name: dbt prod build
        uses: ./.github/actions/run_cli
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          script: |
            dbt debug
            dbt deps
            dbt build --exclude contracts
            dbt run-operation cleanup --args '{dry_run: False}'
            dbt docs generate

      - name: dbt prod contracts
        uses: ./.github/actions/run_cli
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          script: |
            dbt debug
            dbt deps
            dbt build -s contracts
            
      - name: upload target artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: dbt_artifacts
          path: |
            target
            logs
            
      - name: upload prod pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: target

      - name: deploy prod pages
        uses: actions/deploy-pages@v4