name: deploy-pypi
on:
  workflow_dispatch: {}
  push:
    # branches:
    #   - main
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '0 4 * * SAT'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pypi  
    env:
      PIP_REQUIRE_VIRTUALENV: true
      DBT_PYPI_EARLIEST_DOWNLOAD_DATE: ${{ vars.DBT_PYPI_EARLIEST_DOWNLOAD_DATE }}
      DBT_MAX_GIGABYTES_BILLED: ${{ vars.DBT_MAX_GIGABYTES_BILLED }}
    permissions:
        contents: read
        id-token: write
        actions: read
        pages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup_workflow
        uses: ./.github/actions/setup_default_workflow
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      - name: ensure_schema_objects
        uses: ./.github/actions/run_in_venv
        with:
          script: |
            dbt debug
            dbt deps
            dbt run-operation ensure_datasets