name: deploy-to-gcp
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * SAT'

env:
  PIP_REQUIRE_VIRTUALENV: true
  DBT_MAX_GIGABYTES_BILLED: ${{ vars.DBT_MAX_GIGABYTES_BILLED }}

jobs:
  refresh-pypi:
    uses: ./.github/workflows/deploy_pypi.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  refresh-safety:
    uses: ./.github/workflows/deploy_safety.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  refresh_vulns:
    uses: ./.github/workflows/deploy_vulns.yml
    permissions:
      contents: read
      id-token: write
      actions: read
      pages: write
    needs:
      - refresh-safety
      - refresh-pypi
    secrets: inherit
    